name: "Test Multiple Jobs"on:
workflow_dispatch:

jobs:
startupjob:
name: Start Up
steps:
- name: Set Everything Up
run: exit 0 testsjob:
name: Run Tests
needs: startupjob
steps:
- name: Run the test suite
run: exit 0 teardownjob:
name: Tear Down
needs: testsjob
if: always()
steps:
- name: Tear Down
run: exit 0

- name: Notify via Endid
uses: endid-app/endid-github-action@v2.1
if: always()
with:
token: ${{ secrets.ENDID_TOKEN }}
status: ${{ job.status }}
